version: "3.9"
services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Admin$123_"
      ACCEPT_EULA: "Y"
      
  backend:
    image: bloghs/api:1.0
    ports:
      - "5022:80"
    build:
      context: ./
      dockerfile: ./docker/backend/Dockerfile

  frontend:
    image: bloghs/client:1.0
    ports:
      - "4200:80"
    build:
      context: ./
      dockerfile: ./docker/frontend/Dockerfile
  
    
  
